import type { Metadata } from "next";
import "./globals.css";
import Provider from "./Components/Provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>  
      <Provider>
          {children}
      </Provider>
      </body>
      </html>
  );
}
